### ISSUE TITLE
Why dGPU doesn't support Images and Samplers API?

### ISSUE THREAD

**Issue by oscarbg** [HSAFoundation/HSA-Runtime-AMD#15]
Hi,
I see  Images and Samplers API on KAVERI™ and CARRIZO™ chipsets..
why Fiji Fury dGPU via ROCK ROCR doesn't support?
Fundamental HW limitation or software limitation that can be fixed?

**Comment by gstoner** [comment]
As we said in the blog this ROCK and ROCR is  early access developer release,   We will be adding this feature  at future date.


On Jan 28, 2016, at 6:38 AM, Oscar Barenys <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
I see Images and Samplers API on KAVERI™ and CARRIZO™ chipsets..
why Fiji Fury dGPU via ROCK ROCR doesn't support?
Fundamental HW limitation or software limitation that can be fixed?

**Comment by oscarbg** [comment]
Thanks good to know..
a question about HSA Windows support? and dGPU HSA support on Windows?
is supported officially? I say because
seems Windows driver ships (or shipped once a time) with newhsacore64.dll and I found a project 
(https://github.com/hpcgarage/HSA-SDK-Demo) which seems to use that library to create a simple HSA app on Windows..
so Windows HSA library (newhsacore64.dll) already supports dGPUs (Fiji Fury?) like this effort (ROCR) does?

**Comment by jedwards-AMD** [comment]
**There is no support for HSA on windows.** If you look at that link (HSA-SDK-Demo) you will see the following statement:

"Unofficial HSA SDK
This repository hosts unofficial and unsupported headers for Heterogenious System Architecture (HSA) libraries.

The headers let you write applications which directly access low-level HSA interface, bypassing the OpenCL framework on top of it."

In no way does AMD sanction the use of this library or claim support for HSA platforms on windows.
