### ISSUE TITLE
hsa_ext_finalize_program cannot take more than one finalization request at a time

### ISSUE THREAD

**Issue by alienanthill** [HSAFoundation/HSA-Runtime-AMD#3]
hsa_status_t HSA_API hsa_ext_finalize_program(
  hsa_ext_program_handle_t program,
  hsa_agent_t agent,
  size_t finalization_request_count,
  hsa_ext_finalization_request_t *finalization_request_list,
  hsa_ext_control_directives_t *control_directives,
  hsa_ext_error_message_callback_t error_message_callback,
  uint8_t optimization_level,
  const char *options,
  int debug_information);

finalization_request_count cannot be greater than one

**Comment by kzhuravl-AMD** [comment]
Outdated API
