### ISSUE TITLE
1.0P HSA runtime

### ISSUE THREAD

**Issue by whchung** [HSAFoundation/HSA-Runtime-AMD#9]
Is it possible to have access to HSA runtime 1.0P?  All previous commit history were gone and only 1.0F is on github now.  However none of HSAIL compiler (HSAIL-HLC-Stable, HSAIL-HLC-Development, HSAIL-HLC-Development-LLVM) works with 1.0F.

**Comment by johnbridgman** [comment]
Can you please go to the HSA Runtime project and click on the "Releases" tab ? I believe the previous releases were moved to the archive section but are still available. I downloaded the archive (github messages say "source code" but it's really the binaries) and it looked OK at first glance.

**Comment by whchung** [comment]
Sorry I overlooked "Releases" tab.  I can find old releases there.  Thanks a lot for your help!
